/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "#f7f9fb",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: "#3F95EC",
        secondary: "#565e74",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "custom-gray": "#F3F4F6",

        "on-primary-container": "#efefff",
        "tertiary-container": "#007d55",
        "primary-fixed": "#dde1ff",
        "tertiary-fixed-dim": "#4edea3",
        "on-error": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#0035be",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#124af0",
        "on-primary-fixed": "#001356",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#bdffdb",
        "on-tertiary-fixed": "#002113",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8ea",
        "surface-container": "#eceef0",
        "on-surface-variant": "#434656",
        tertiary: "#006242",
        outline: "#747688",
        surface: "#f7f9fb",
        "primary-fixed-dim": "#b8c3ff",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#dae2fd",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#dae2fd",
        error: "#ba1a1a",
        "outline-variant": "#c4c5d9",
        "on-secondary-fixed": "#131b2e",
        "on-surface": "#4b5563",
        "inverse-primary": "#b8c3ff",
        "surface-dim": "#d8dadc",
        "surface-container-low": "#f2f4f6",
        "on-background": "#191c1e",
        "primary-container": "#2e5bff",
        "on-secondary-container": "#5c647a",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#3f465c",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
